# Permission: scheck.admin
#


message:
  noPerm: "&cУ вас нет прав!"
  sender: "&6Check &7» &6Игрок &c&n%target%&6 вызван на проверку"
  isCheck: "&6Check &7» &6Игрока проверяет другой модератор %moder%"
  already: "&6Check &7» &6Вы уже находитесь на проверке"
  removeCheck: "&6Check &7» &6Вы сняли проверку игроку %target%"
  start:
    title: "&cПроверка на читы"
    subTitle: "&fВсе инструкции находятся в чате"
    timeIn: 40
    stay: 20
    timeOut: 20
    target:
      - '&4&lВНИМАНИЕ! &7Вы были вызваны на §cПроверку читов'
      - ''
      - '&cПишите свой дискорд ник в чат. &7У вас есть 3 минуты'
      - '&7Если у вас мут, то пишите сообщение в чат (Модератор увидит)'
      - ''
      - '&7Признание в использовани читов - &c46 дней бана'
      - '&7За выход с сервера во время проверки - &c50 дней бана'
      - ''
      - '&7Модератору на проверке &cзапрещено &7скидывать вам'
      - '&7различные команды для ПК (powershell, cmd), а так же ссылки'
      - '&7на скачивание программ.'
      - ''
      - '&7Увидели нарушение со стороны модератора, фиксируйте это'
      - '&7и сообщайте нам об этом на форум &cсервер'
      - ''

  moder:
    sendMsg: "&7Игрок %target% пишет вам -> &f%msg%"
    reply: "&7Сообщение было отправленно модератору"

settings:
  disableCommand:
    enable: true
    text: "&7Вы не можете выполнять команды на проврке!"
    sendModer: "Игрок отправил команду %command%"
  banPlayer:
    enable: true
    text: "&aИгрок вышел и получил баньчик бананьчик"
    command: "tempban %target% 1m дебил"
  disableChat:
    enable: true
    text: "&cВы не можете писать в чат пока на проверке!"
    sendModer: "Игрок отправил в чат %msg%"


help:
  - "&cВы не правильно ввели команду!"
  - "&cИспользуйте /check <ник>"





